<!DOCTYPE html>
<html>
<head>
	<title>Css Demo</title>
	<link rel="stylesheet" type="text/css" href="./css/new.css">
</head>
<body>


<a href="css.php"> Click Here </a>

<hr>

<div>

	<div class="cls" ID="div1">
		div 1 div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1
		div 1 div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1
		div 1 div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1div 1
	</div>
	
	<div  class="cls">
		div 2
	</div>
	<div  class="cls">
		div 3
	</div>
</div>





</body>
</html>